### ISSUE TITLE
Slash commands seems not working

### ISSUE THREAD

**Issue by Am4rokTV** [qpn6ph9q/ashesofcreation.wiki.bot#1]
/random or other doesnt work
but !random no problem :S

**Comment by qpn6ph9q** [comment]
It may be some kind of permissions problem? Try kicking and [reinviting](https://goo.gl/DMB3Sr) the bot.

**Comment by qpn6ph9q** [comment]
This was due to the invite link not being updated on top.gg. 

Kicking the bot and re-inviting using this link should fix the problem https://top.gg/bot/506608731463876628
